version: "3.8"

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    networks:
      - software
    volumes:
      - $PWD/mongo-data:/data/db'

networks:
  software:
    driver: bridge
